# syntax=docker/dockerfile:experimental

FROM node:18-alpine3.16
WORKDIR /
RUN apk update
RUN apk add --no-cache bash
RUN apk add git
RUN apk add openssh
EXPOSE 3000
EXPOSE 3006
RUN /bin/bash
ENTRYPOINT [ "/entrypoint.sh" ]