version: "3.5"

services:
  domain-services:
    ports:
      - 3002:3002
    volumes:
      - "C:/Users/micha/.ssh/id_rsa:/root/.ssh/id_rsa:ro"
      - "C:/Users/micha/.ssh/known_hosts:/root/.ssh/known_hosts"
      - "C:/Users/micha/.gitconfig:/root/.gitconfig:ro"
      - "./entrypoint.d:/entrypoint.d:ro"
    tty: true
    build:
      dockerfile: dockerfiles