version: "3.5"

networks:
  domain-network:
    external: true

services:
  domain-services:
    image: domain-service
    ports:
      - 3002:3002
    volumes:
      - "C:/Users/micha/.ssh/id_rsa:/root/.ssh/id_rsa:ro"
      - "C:/Users/micha/.ssh/known_hosts:/root/.ssh/known_hosts"
      - "C:/Users/micha/.gitconfig:/root/.gitconfig:ro"
      - "./entrypoint.sh:/entrypoint.sh"
      - "./entrypoint.d:/entrypoint.d:ro"
    tty: true
    build:
      dockerfile: dockerfile
    networks:
      - domain-network
    environment:
    - APPLICATION_DATABASE=jdbc:mysql://capstone-database:3306/Capstone
    - APPLICATION_DATABASE_USER=springuser
    - APPLICATION_DATABASE_USER_PASS=ThePassword
    - APPLICATION_PORT=3002
    - FRONTEND_URL=http://localhost:3000